version: "3.8"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./ops/.env
    ports:
      - "5432:5432"
    volumes:
      - ./ops/postgres_schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/postgres:/var/lib/postgresql/data

  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  app:
    build:
      context: .
      dockerfile: ops/app.Dockerfile
    env_file: ./ops/.env
    restart: on-failure
    depends_on:
      - db
      - cache
    networks:
      - default
    ports:
      - "8081:8081"

  kafka:
    image: wurstmeister/kafka
    volumes:
      - ./data/kafka:/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    hostname: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"

  zookeeper:
    image: zookeeper
    volumes:
      - ./data/zookeeper:/data
    ports:
      - "2181:2181"

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - ./ops/clickhouse_schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/clickhouse:/var/lib/clickhouse
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - "8123:8123"

