version: "3.8"
services:
  db:
    build:
      context: ./ops
      dockerfile: db.Dockerfile
    restart: always
    env_file:
      - ./ops/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  app:
    build:
      context: .
      dockerfile: ops/app.Dockerfile
    env_file: ./ops/.env
    restart: on-failure
    depends_on:
      - db
      - cache
    networks:
      - default
    ports:
      - "8081:8081"
volumes:
  data:
  redis_data:
