version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: ./..
      dockerfile: ops/app.Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8081:8081"
volumes:
  data:
